### ISSUE TITLE
Lista de Materiais

### ISSUE THREAD

**Issue by nicowxd** [nicowxd/smartHome#1]
Definir a lista de materiais juntamente com o preço encontrado para cada componente.

**Comment by MileneBorba** [comment]
1. Arduino Uno
2. 3 Lâmpadas E14 15W
3. Módulo Relé SRD - O5VDC -SL -C
4. Fio Simples 1mm
5. Soquete Lâmpada E14 15W
6. Fonte DC Chaveada 9V iA Plug P4
7. Módulo Wi-Fi ESP8266 ESP-I2F
